site_name: Tuhi - App Documentation
nav:
  - Home: /docs/index.md
  - FAQs: /docs/FAQ.md
  - Privacy: /docs/PrivacyStatement.md
  - Terms and Conditions: /docs/terms.md
theme: jekyll-theme-just-the-docs
